apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec33nw-analytics
  labels:
    app: ec33nw-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec33nw-analytics
  template:
    metadata:
      labels:
        app: ec33nw-analytics
    spec:
      containers:
      - name: ec33nw-analytics
        image: zedas/ec33nw-map-analytics
        ports:
        - containerPort: 8081
        - containerPort: 8981
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: ec33nw-analytics-service
spec:
  selector:
    app: ec33nw-analytics
  ports:
    - port: 8081
      name: resttestport
      protocol: TCP
      targetPort: 8081
    - port: 8981
      name: grcpport
      protocol: TCP
      targetPort: 8981
      


